== CloudWatch Metrics
Spring Cloud AWS provides Spring Boot auto-configuration for Micrometer CloudWatch integration.
To send metrics to CloudWatch add a dependency to `micrometer-registry-cloudwatch` module:

[source,xml,indent=0]
----
<dependency>
	<groupId>io.micrometer</groupId>
	<artifactId>micrometer-registry-cloudwatch2</artifactId>
</dependency>
----

Additionally, CloudWatch integration requires a value provided for `management.cloudwatch.metrics.export.namespace` configuration property.

Following configuration properties are available to configure CloudWatch integration:

[cols="3*", options="header"]
|===
|property
|default
|description

|management.cloudwatch.metrics.export.namespace
|
|The namespace which will be used when sending metrics to CloudWatch. This property is needed and must not be null.

|management.cloudwatch.metrics.export.step
|1m
|The interval at which metrics are sent to CloudWatch. The default is 1 minute.

|spring.cloud.aws.cloudwatch.enabled
|true
|If CloudWatch integration should be enabled. This property should be likely set to `false` for a local development profile.

|spring.cloud.aws.cloudwatch.endpoint
|
|Overrides the default endpoint.

|spring.cloud.aws.cloudwatch.region
|
|The specific region for CloudWatch integration.
|===

=== Client Customization

`CloudWatchAsyncClient` can be further customized by providing a bean of type `CloudWatchAsyncClientCustomizer`:

[source,java]
----
@Bean
CloudWatchAsyncClientCustomizer customizer() {
	return builder -> {
		builder.overrideConfiguration(builder.overrideConfiguration().copy(c -> {
			c.apiCallTimeout(Duration.ofMillis(1500));
		}));
	};
}
----

[WARNING]
====
`builder.overrideConfiguration(..)` replaces the configuration object, so always make sure to use `builder.overrideConfiguration().copy(c -> ..)` to configure only certain properties and keep the already pre-configured values for others.
====

`CloudWatchAsyncClientCustomizer` is a functional interface that enables configuring `CloudWatchAsyncClientBuilder` before the `CloudWatchAsyncClient` is built in auto-configuration.

There can be multiple `CloudWatchAsyncClientCustomizer` beans present in single application context. `@Order(..)` annotation can be used to define the order of the execution.

Note that `CloudWatchAsyncClientCustomizer` beans are applied **after** `AwsAsyncClientCustomizer` beans and therefore can overwrite previously set configurations.
