== CloudWatch Metrics
Spring Cloud AWS provides Spring Boot auto-configuration for Micrometer CloudWatch integration.
To send metrics to CloudWatch add a dependency to `micrometer-registry-cloudwatch` module:

[source,xml,indent=0]
----
<dependency>
	<groupId>io.micrometer</groupId>
	<artifactId>micrometer-registry-cloudwatch</artifactId>
</dependency>
----

Additionally CloudWatch integration requires a value provided for `management.metrics.export.cloudwatch.namespace` configuration property.

Following configuration properties are available to configure CloudWatch integration:

[cols="3*", options="header"]
|===
|property
|default
|description

|management.metrics.export.cloudwatch.namespace
|
|The namespace which will be used when sending metrics to CloudWatch. This property is needed and must not be null.

|management.metrics.export.cloudwatch.enabled
|true
|If CloudWatch integration should be enabled. This property should be likely set to `false` for a local development profile.

|management.metrics.export.cloudwatch.region
|
|The specific region for CloudWatch integration.

|management.metrics.export.cloudwatch.step
|1m
|The interval at which metrics are sent to CloudWatch. The default is 1 minute.
|===
