[#spring-cloud-aws-parameter-store]
== Spring Cloud AWS Parameter Store

Spring Cloud AWS adds support for loading configuration properties from Parameter Store through Spring Boot https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-files-importing[config import feature].

Maven coordinates, using <<index.adoc#bill-of-materials, Spring Cloud AWS BOM>>:

[source,xml]
----
<dependency>
    <groupId>io.awspring.cloud</groupId>
    <artifactId>spring-cloud-starter-aws-parameter-store</artifactId>
</dependency>
----

=== Loading External Configuration

Once the dependency is there, its possible to load external configuration using:

[source,properties]
----
spring.config.import=aws-parameterstore:/path/in/parameter/store/
----

TODO

=== Customizing SSMClient

TODO

=== Customizing CredentialsProvider

TODO

=== Configuration

The Spring Boot Starter for Parameter Store provides the following configuration options:

[cols="4,3,1,1"]
|===
| Name | Description | Required | Default value
| `spring.cloud.aws.parameterstore.enabled` | Enables the Parameter Store integration. | No | `true`
| `spring.cloud.aws.parameterstore.endpoint` | Configures endpoint used by `SsmClient`. | No | `http://localhost:4566`
| `spring.cloud.aws.parameterstore.region` | Configures region used by `SsmClient`. | No | `eu-west-1`
|===

=== IAM Permissions
Following IAM permissions are required by Spring Cloud AWS:

[cols="2"]
|===
| Get parameter from specific path
| `ssm:GetParametersByPath`
|===

Sample IAM policy granting access to Parameter Store:

[source,json,indent=0]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "ssm:GetParametersByPath",
            "Resource": "yourArn"
        }
    ]
}
----
