= 🍃 Spring Cloud for Amazon Web Services

Spring Cloud AWS, part of the Spring Cloud umbrella project, eases the integration with hosted Amazon Web Services. It offers a convenient way to interact with AWS provided services using well-known Spring idioms and APIs, such as the messaging or caching API. Developers can build their application around the hosted services without having to care about infrastructure or maintenance.

* http://awspring.io/[Official Website]

* https://docs.awspring.io/spring-cloud-aws/docs/2.3.0-RC1/reference/html/index.html[Reference Guide]

= Checking out and building

To check out the project and build it from source, do the following:

--------------------------------------------------------------
git clone https://github.com/awspring/spring-cloud-aws.git
cd spring-cloud-aws
./mvnw package
--------------------------------------------------------------

To build and install jars into your local Maven cache:

-----------
./mvnw install
-----------

= Building documentation

Documentation can be built by activating the `docs` profile in the maven
build.

-----------
./mvnw package -Pdocs
-----------

= Getting in touch

* https://github.com/awspring/spring-cloud-aws/discussions[Discussions on Github] - the best way to discuss anything Spring Cloud AWS related
* https://gitter.im/spring-cloud/spring-cloud-aws[Spring Cloud AWS channel on Gitter]

Or reach out directly to individual team members:

* Maciej Walkowiak https://twitter.com/maciejwalkowiak[Twitter]
* Eddú Meléndez https://twitter.com/EdduMelendez[Twitter]
* Matej Nedic https://twitter.com/MatejNedic1[Twitter]

= Using IntelliJ IDEA

Spring Cloud AWS development is done with
https://www.jetbrains.com/idea/[IntelliJ IDEA]. In order to create all
https://www.jetbrains.com/idea/[IntelliJ IDEA] project files, you have to
import the file within idea as a maven project.

_Note:_ Please make sure to revert all changes in the .idea config file
directory, as the maven plugin overwrites the configuration files kept
in the scm.

= Running integration tests

Spring Cloud AWS contains a test-suite which runs integration tests to
ensure compatibility with the Amazon Web Services. In order to run the
integration tests, the build process has to create different resources
on the Amazon Webservice platform (Amazon EC2 instances, Amazon RDS
instances, Amazon S3 Buckets, Amazon SQS Queues). Creating these
resources takes time and costs money, because every instance creation is
charged with a one hour usage. Therefore Spring Cloud AWS does not
execute the integration tests by default.

In order to run integration tests you must prepare three properties named accessKey,secretKey and rdsPassword. These two
properties accessKey and secretKey are account/user specific and should
never be shared to anyone. To retrieve these settings you have to open
your account inside the AWS console and retrieve them through the
https://portal.aws.amazon.com/gp/aws/securityCredentials[Security
Credentials Page]. _Note:_ In general we recommend that you use an
https://aws.amazon.com/iam/[Amazon IAM] user instead of the account
itself. The last password rdsPassword is used to access the database
inside the integration tests. This password has a minimum length of 8
characters.

Also you must prepare the sender and recipient mail addresses to test the
https://aws.amazon.com/ses/[Amazon Simple E-Mail Service]. These two
addresses must be verified for the Amazon SES Service.

To build with the integration tests you must execute

-----------------------------------------------------------------------------------------------------
mvn verify -Daws-integration-tests.access-key=<access key>  -Daws-integration-tests.secret-key=<secret key> -DrdsPassword=<rds password> -DsenderAddress=<sender address> -DrecipientAddress=<recipient address>
-----------------------------------------------------------------------------------------------------

The integration test will create an
https://aws.amazon.com/de/cloudformation/[Amazon Web Services
CloudFormation] stack and execute the tests. The stack is destroyed
after executing the tests (either successful or failed) to ensure that
there are no unnecessary costs.

= Costs of integration tests

The costs for one integration test run should not be more than 0.40 $
per hour (excl. VAT).

= Developing using Amazon Web Services

During the development, it might be time-consuming to run the integration
tests regularly. In order to create a stack only once, and reuse them
for the tests run, you have to create the stack manually using the
template found in /spring-cloud-aws-integration-test/src/test/resources.
You will need to create the stack with the name "IntegrationTestStack"
to ensure that the integration tests will re-use the stack.

== Contributing

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/contributing.adoc[]
