= 🍃 Spring Cloud for Amazon Web Services

Spring Cloud AWS, part of the Spring Cloud umbrella project, eases the integration with hosted Amazon Web Services. It offers a convenient way to interact with AWS provided services using well-known Spring idioms and APIs, such as the messaging or caching API. Developers can build their application around the hosted services without having to care about infrastructure or maintenance.

* http://awspring.io/[Official Website]

* https://docs.awspring.io/spring-cloud-aws/docs/2.3.0-RC1/reference/html/index.html[Reference Guide]

= Checking out and building

To check out the project and build it from source, do the following:

--------------------------------------------------------------
git clone https://github.com/awspring/spring-cloud-aws.git
cd spring-cloud-aws
./mvnw package
--------------------------------------------------------------

To build and install jars into your local Maven cache:

-----------
./mvnw install
-----------

= Building documentation

Documentation can be built by activating the `docs` profile in the maven
build.

-----------
./mvnw package -Pdocs
-----------

= Getting in touch

* https://github.com/awspring/spring-cloud-aws/discussions[Discussions on Github] - the best way to discuss anything Spring Cloud AWS related
* https://gitter.im/spring-cloud/spring-cloud-aws[Spring Cloud AWS channel on Gitter]

Or reach out directly to individual team members:

* Maciej Walkowiak https://twitter.com/maciejwalkowiak[Twitter]
* Eddú Meléndez https://twitter.com/EdduMelendez[Twitter]
* Matej Nedic https://twitter.com/MatejNedic1[Twitter]
