= Spring Cloud for Amazon Web Services

include::intro.adoc[]

= Checking out and building
To check out the project and build it from source, do the following:

--------------------------------------------------------------
git clone https://github.com/spring-cloud/spring-cloud-aws.git
cd spring-cloud-aws
mvn package
--------------------------------------------------------------

If you encounter out of memory errors during the build, increase
available heap and permgen for Maven:

-------------------------------------------
MAVEN_OPTS='-XX:MaxPermSize=258m -Xmx1024m'
-------------------------------------------

To build and install jars into your local Maven cache:

-----------
mvn install
-----------

= Building documentation
Documentation can be built by activating the `docs`profile in the maven
build. If there is an ruby error like

--------------------------------------------------------------
LoadError: no such file to load -- asciidoctor
--------------------------------------------------------------

then the user must install the _asciidoctor_ gem and set the environment
variable `GEM_HOME`to the ruby gem folder. For example:

-------------------------------------------------------------
  # Get gem info
  gem environment

  export GEM_HOME=<PATH FOR GEM ENVIRONMENT>

-------------------------------------------------------------

= Using IntelliJ IDEA
Spring Cloud AWS development is done with
https://www.jetbrains.com/idea/[IntelliJ IDEA]. In order to create all
https://www.jetbrains.com/idea/[IntelliJ IDEA] project files, you have to
import the file within idea as a maven project.

_Note:_ Please make sure to revert all changes in the .idea config file
directory, as the maven plugin overwrites the configuration files kept
in the scm.

= Running integration tests

Spring Cloud AWS contains a test-suite which runs integration tests to
ensure compatibility with the Amazon Web Services. In order to run the
integration tests, the build process has to create different resources
on the Amazon Webservice platform (Amazon EC2 instances, Amazon RDS
instances, Amazon S3 Buckets, Amazon SQS Queues). Creating these
resources takes time and costs money, because every instance creation is
charged with a one hour usage. Therefore Spring Cloud AWS does not
execute the integration tests by default.

In order to execute the integration tests you have to create two
configuration files that configure the necessary parameters to build the
environment.

Please create a new file named access.properties. This file must contain
three properties named accessKey,secretKey and rdsPassword. These two
properties accessKey and secretKey are account/user specific and should
never be shared to anyone. To retrieve these settings you have to open
your account inside the AWS console and retrieve them through the
https://portal.aws.amazon.com/gp/aws/securityCredentials[Security
Credentials Page]. _Note:_ In general we recommend that you use an
https://aws.amazon.com/iam/[Amazon IAM] user instead of the account
itself. The last password rdsPassword is used to access the database
inside the integration tests. This password has a minimum length of 8
characters.

An example file will look like this

-------------------------------------------
cloud.aws.credentials.accessKey=ilaugsjdlkahgsdlaksdhg
cloud.aws.credentials.secretKey=aöksjdhöadjs,höalsdhjköalsdjhasd+
rdsPassword=someVerySecretPassword
-------------------------------------------

Also you have to create another file named mail.properties which will
provide the sender and recipient mail address to test the
https://aws.amazon.com/ses/[Amazon Simple E-Mail Service]. These two
addresses must be verified for the Amazon SES Service.

An example file will have the following contents

----------------------------
senderAddress=foo@bar.com
recipientAddress=baz@buz.com
----------------------------

After creating both files and storing them outside the project (or
inside the project, they are ignored in git) you have to provide the
configuration directory when running the build. Providing these
configuration settings will automatically execute the integration tests.

To build with the integration tests you must execute

-----------------------------------------------------------------------------------------------------
mvn verify -Dels.config.dir=/Users/foo/config/dir
(on windows you will also need a leading slash before the drive letter e.g. /C:/users/foo/config/dir)
-----------------------------------------------------------------------------------------------------

The integration test will create an
https://aws.amazon.com/de/cloudformation/[Amazon Web Services
CloudFormation] stack and execute the tests. The stack is destroyed
after executing the tests (either successful or failed) to ensure that
there are no unnecessary costs.

= Costs of integration tests
The costs for one integration test run should not be more than 0.40 $
per hour (excl. VAT).


= Developing using Amazon Web Services

During development it might be time-consuming to run the integration
tests regularly. In order to create a stack only once, and reuse them
for the tests run, you have to create the stack manually using the
template found in /spring-cloud-aws-integration-test/src/test/resources.
You will need to create the stack with the name "IntegrationTestStack"
to ensure that the integration tests will re-use the stack.

= Getting in touch

Spring Cloud Team on https://twitter.com/springcentral[Twitter]

Individual team members can be found on different social media channels

* Agim Emruli (https://twitter.com/aemruli[Twitter] /
https://de.linkedin.com/in/agimemruli[LinkedIn])
* Alain Sahli (https://twitter.com/sahlialain[Twitter] /
https://ch.linkedin.com/in/asahli[LinkedIn])
* Christian Stettler (https://twitter.com/chrisstettler[Twitter])

== Contributing

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/contributing.adoc[]
