[#spring-cloud-aws-s3]
== S3 integration

https://aws.amazon.com/s3/[S3] allows storing files in the cloud.
A Spring Boot starter is provided to auto-configure the various S3 integration related components.

Maven coordinates, using <<index.adoc#bill-of-materials, Spring Cloud AWS BOM>>:

[source,xml]
----
<dependency>
    <groupId>io.awspring.cloud</groupId>
    <artifactId>spring-cloud-aws-starter-s3</artifactId>
</dependency>
----

=== Using S3 client

The starter automatically configures and registers an `S3Client` bean in the Spring application context. The `S3Client` bean can be used to perform operations on S3 buckets and objects.

[source,java]
----
import java.io.IOException;
import java.nio.charset.StandardCharsets;

import software.amazon.awssdk.core.ResponseInputStream;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.GetObjectResponse;

import org.springframework.stereotype.Component;
import org.springframework.util.StreamUtils;

@Component
class S3ClientSample {
	private final S3Client s3Client;

	S3ClientSample(S3Client s3Client) {
		this.s3Client = s3Client;
	}

	void readFile() throws IOException {
		ResponseInputStream<GetObjectResponse> response = s3Client.getObject(
			request -> request.bucket("bucket-name").key("file-name.txt"));

		String fileContent = StreamUtils.copyToString(response, StandardCharsets.UTF_8);

		System.out.println(fileContent);
	}
}
----
=== Using S3TransferManager and the CRT-based S3 client

AWS https://aws.amazon.com/blogs/developer/introducing-crt-based-s3-client-and-the-s3-transfer-manager-in-the-aws-sdk-for-java-2-x/[launched] a high-level file transfer utility, called Transfer Manager, and a CRT-based S3 client.

The starter automatically configures and registers a `software.amazon.awssdk.transfer.s3.S3TransferManager` bean if the following dependency is added to the project:

[source,xml]
----
<dependency>
  <groupId>software.amazon.awssdk</groupId>
  <artifactId>s3-transfer-manager</artifactId>
</dependency>
----

Transfer Manager works best with the CRT-based S3 client. To auto-configure a CRT-based `S3AsyncClient`, add the following dependency to your project:

[source,xml]
----
<dependency>
  <groupId>software.amazon.awssdk</groupId>
  <artifactId>aws-crt-client</artifactId>
</dependency>
----

When no `S3AsyncClient` bean is created, the default `S3AsyncClient` provided by the AWS SDK is used. To benefit from maximum throughput, multipart upload/download, and resumable file upload, consider using a CRT-based `S3AsyncClient`.

=== S3 objects as Spring Resources

https://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html[Spring Resources] are an abstraction for a number of low-level resources, such as file system files, classpath files, servlet context-relative files, etc.
Spring Cloud AWS adds a new resource type: an `S3Resource` object.

The Spring resource abstraction for S3 allows S3 objects to be accessed by their S3 URL using the `@Value` annotation:

[source,java]
----
@Value("s3://[S3_BUCKET_NAME]/[FILE_NAME]")
private Resource s3Resource;
----

...or the Spring application context:

[source,java]
----
SpringApplication.run(...).getResource("s3://[S3_BUCKET_NAME]/[FILE_NAME]");
----


This creates a `Resource` object that can be used to read the file, among https://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html#resources-resource[other possible operations].

It is also possible to write to a `Resource`, although a `WriteableResource` is required.

[source,java]
----
@Value("s3://[S3_BUCKET_NAME]/[FILE_NAME]")
private Resource s3Resource;
...
try (OutputStream os = ((WritableResource) s3Resource).getOutputStream()) {
  os.write("content".getBytes());
}
----

To work with the `Resource` as an S3 resource, cast it to `io.awspring.cloud.s3.S3Resource`.
Using `S3Resource` directly lets you set the https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html[S3 object metadata].

[source,java]
----
@Value("s3://[S3_BUCKET_NAME]/[FILE_NAME]")
private Resource s3Resource;
...
ObjectMetadata objectMetadata = ObjectMetadata.builder()
    .contentType("application/json")
    .serverSideEncryption(ServerSideEncryption.AES256)
    .build();
s3Resource.setObjectMetadata(objectMetadata);
try (OutputStream outputStream = s3Resource.getOutputStream()) {
    outputStream.write("content".getBytes(StandardCharsets.UTF_8));
}
----

=== S3 client-side encryption
==== Object keys and prefix locations

A location is parsed into a bucket and an object key. A trailing slash in the key is significant and is preserved:

* `s3://my-bucket/path/file.txt` resolves to the object key `path/file.txt`.
* `s3://my-bucket/path/` resolves to the *prefix* key `path/` (it is not stripped to `path`).
* `s3://my-bucket/` resolves to a bucket-only location with an empty object key.

Because the trailing slash is retained, a prefix location can be used as a Spring static resource handler location, which Spring requires to end with a slash:

[source,java]
----
@Override
public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("/files/**")
        .addResourceLocations("s3://my-bucket/path/");
}
----

[NOTE]
====
Retaining the trailing slash is a behavior change introduced `4.1.0`.
In earlier versions a trailing slash was stripped, so `s3://my-bucket/path/` resolved to the object key `path` instead of `path/`.
If you relied on the previous behavior, drop the trailing slash from your locations (use `s3://my-bucket/path`).
====

=== S3 Client Side Encryption

AWS offers an encryption library integrated with the S3 client, called the https://docs.aws.amazon.com/amazon-s3-encryption-client/latest/developerguide/what-is-s3-encryption-client.html[S3EncryptionClient].
The encryption client encrypts files before they are sent to the S3 bucket.

To auto-configure the encryption client, add the following dependency:

[source,xml]
----
<dependency>
	<groupId>software.amazon.encryption.s3</groupId>
	<artifactId>amazon-s3-encryption-client-java</artifactId>
</dependency>
----


Three types of encryption are supported.

==== KMS key encryption

To configure encryption via a KMS key, set `spring.cloud.aws.s3.encryption.key-id` to the KMS key ARN. That key will then be used to encrypt files.

The following dependency is also required:

[source,xml]
----
<dependency>
 	<groupId>software.amazon.awssdk</groupId>
	<artifactId>kms</artifactId>
 	<optional>true</optional>
 </dependency>
----

==== RSA asymmetric encryption

Asymmetric encryption is supported via RSA. To enable it, implement `io.awspring.cloud.autoconfigure.s3.S3RsaProvider`.

NOTE: You will have to store private and public keys yourself, otherwise you won't be able to decrypt the data later.

An example of a simple `S3RsaProvider`:

[source,java,indent=0]
----
import io.awspring.cloud.autoconfigure.s3.S3RsaProvider;
import java.security.KeyPair;
import java.security.KeyPairGenerator;

public class MyRsaProvider implements S3RsaProvider {
	@Override
	public KeyPair generateKeyPair() {
		try {
			// fetch key pair from secure location such as Secrets Manager
			// access to KeyPair is required to decrypt objects when fetching, so it is advised to keep them stored securely
		}
		catch (Exception e) {
			return null;
		}
	}
}
----

==== AES symmetric encryption

If you want to use a symmetric algorithm, this is possible via `io.awspring.cloud.autoconfigure.s3.S3AesProvider`.

NOTE: Ensure the private key is stored using secure storage mechanisms that prevent unauthorized access.

An example of a simple `S3AesProvider`:

[source,java,indent=0]
----
import io.awspring.cloud.autoconfigure.s3.S3AesProvider;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;

public class MyAesProvider implements S3AesProvider {
	@Override
	public SecretKey generateSecretKey() {
		try {
			// fetch secret key from secure location such as Secrets Manager
        	// access to secret key is required to decrypt objects when fetching, so it is advised to keep them stored securely
		}
		catch (Exception e) {
			return null;
		}
	}
}
----


=== S3 output stream

By default, `S3Resource` uses `io.awspring.cloud.s3.InMemoryBufferingS3OutputStream`. When data is written to the resource, it is sent to S3 using multipart upload.
If a network error occurs during upload, `S3Client` has a built-in retry mechanism that will retry each failed part. If the upload fails after retries, the multipart upload gets aborted and `S3Resource` throws `io.awspring.cloud.s3.S3Exception`.

If `InMemoryBufferingS3OutputStream` behavior does not fit your needs, you can use `io.awspring.cloud.s3.DiskBufferingS3OutputStream` by defining a bean of type `DiskBufferingS3OutputStreamProvider`, which will override the default output stream provider.
With `DiskBufferingS3OutputStream`, when data is written to the resource, it is first stored on disk in a `tmp` directory in the OS. Once the stream gets closed, the file gets uploaded with the https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#putObject-java.util.function.Consumer-java.nio.file.Path-[S3Client#putObject] method.
If a network error occurs during upload, `S3Client` has a built-in retry mechanism. If the upload fails after retries, `S3Resource` throws an `io.awspring.cloud.s3.UploadFailed` exception containing a file location in a temporary directory in the file system.

[source,java]
----
try (OutputStream outputStream = s3Resource.getOutputStream()) {
    outputStream.write("content".getBytes(StandardCharsets.UTF_8));
} catch (UploadFailedException e) {
    // e.getPath contains a file location in temporary folder
}
----

If you are using the `S3TransferManager`, the default implementation will switch to `io.awspring.cloud.s3.TransferManagerS3OutputStream`. This output stream also uses a temporary file to write it to disk before uploading it to S3, but it may be faster as it uses a multi-part upload under the hood.

=== Searching resources

The Spring resource loader also supports collecting resources based on an Ant-style path specification. Spring Cloud AWS
offers the same support to resolve resources within a bucket and even throughout buckets. The actual resource loader needs
to be wrapped with the Spring Cloud AWS one in order to search for S3 buckets. In the case of a non-S3 bucket, the resource loader
will fall back to the original one. The next example shows the resource resolution by using different patterns.

[source,java,indent=0]
----
import org.springframework.context.ApplicationContext;
import org.springframework.core.io.support.ResourcePatternResolver;
import org.springframework.core.io.Resource;

import io.awspring.cloud.s3.S3PathMatchingResourcePatternResolver;

import software.amazon.awssdk.services.s3.S3Client;

public class SimpleResourceLoadingBean {

	private final ResourcePatternResolver resourcePatternResolver;

	@Autowired
	public void setupResolver(S3Client s3Client, ApplicationContext applicationContext) {
		this.resourcePatternResolver = new S3PathMatchingResourcePatternResolver(s3Client, applicationContext);
	}

 	public void resolveAndLoad() throws IOException {
 		Resource[] allTxtFilesInFolder =  this.resourcePatternResolver.getResources("s3://bucket/name/*.txt");
 		Resource[] allTxtFilesInBucket =  this.resourcePatternResolver.getResources("s3://bucket/**/*.txt");
 		Resource[] allTxtFilesGlobally =  this.resourcePatternResolver.getResources("s3://**/*.txt");
 	}
}
----

[WARNING]
====
Resolving resources throughout all buckets can be very time-consuming depending on the number of buckets a user owns.
====

=== Using S3 Access Grants

Sometimes there is a need for fine-grained access control over S3 bucket contents.
Since IAM policies and S3 bucket policies are limited to 10 KB in size, S3 Access Grants addresses this by enabling fine-grained access control over objects in a bucket.

To use S3 Access Grants with `S3Client` and `S3Template`, add the following plugin:

[source,xml]
----
<dependency>
	<groupId>software.amazon.s3.accessgrants</groupId>
	<artifactId>aws-s3-accessgrants-java-plugin</artifactId>
</dependency>
----

=== Using S3Template

Spring Cloud AWS provides a higher-level abstraction on top of `S3Client`, offering methods for the most common use cases when working with S3.

In addition to self-explanatory methods for creating and deleting buckets, `S3Template` provides simple methods for uploading and downloading files:

[source,java]
----
@Autowired
private S3Template s3Template;

InputStream is = ...
// uploading file without metadata
s3Template.upload(BUCKET, "file.txt", is);

// uploading file with metadata
s3Template.upload(BUCKET, "file.txt", is, ObjectMetadata.builder().contentType("text/plain").build());
----

Another feature of `S3Template` is the ability to generate signed URLs for getting/putting S3 objects in a single method call:
[source,java]
----
URL signedGetUrl = s3Template.createSignedGetURL("bucket_name", "file.txt", Duration.ofMinutes(5));
----

`S3Template` also allows storing and retrieving Java objects.

[source,java]
----
Person p = new Person("John", "Doe");
s3Template.store(BUCKET, "person.json", p);

Person loadedPerson = s3Template.read(BUCKET, "person.json", Person.class);
----

By default, if Jackson 3 is on the classpath, `S3Template` uses the `JsonMapper`-based `Jackson2JsonS3ObjectConverter` to convert from S3 object to Java object and vice versa.
If Jackson 3 is not on the classpath and Jackson 2 is, `S3Template` uses the `ObjectMapper`-based `LegacyJackson2JsonS3ObjectConverter` to convert from S3 object to Java object and vice versa.
This behavior can be overridden by providing a custom bean of type `S3ObjectConverter`.

=== Determining S3 object content type

All S3 objects stored in S3 through `S3Template`, `S3Resource` or `S3OutputStream` automatically get a `contentType` property set on the S3 object metadata, based on the S3 object key (file name).

By default, `PropertiesS3ObjectContentTypeResolver` - a component supporting over 800 file extensions - is responsible for content type resolution.
If this content type resolution does not meet your needs, you can provide a custom bean of type `S3ObjectContentTypeResolver`, which will be automatically used in all components responsible for uploading files.

=== Configuration

The Spring Boot Starter for S3 provides the following configuration options:

[cols="2,3,1,1"]
|===
| Name | Description | Required | Default value
| `spring.cloud.aws.s3.enabled` | Enables the S3 integration. | No | `true`
| `spring.cloud.aws.s3.endpoint` | Configures the endpoint used by `S3Client`. | No | `http://localhost:4566`
| `spring.cloud.aws.s3.region` | Configures the region used by `S3Client`. | No | `eu-west-1`
| `spring.cloud.aws.s3.accelerate-mode-enabled` | Option to enable using the accelerate endpoint when accessing S3. Accelerate endpoints allow faster transfer of objects by using Amazon CloudFront's globally distributed edge locations. | No | `null` (falls back to SDK default)
| `spring.cloud.aws.s3.checksum-validation-enabled` | Option to disable doing a validation of the checksum of an object stored in S3. | No | `null` (falls back to SDK default)
| `spring.cloud.aws.s3.chunked-encoding-enabled` | Option to enable using chunked encoding when signing the request payload for `PutObjectRequest` and `UploadPartRequest`. | No | `null` (falls back to SDK default)
| `spring.cloud.aws.s3.path-style-access-enabled` | Option to enable using path style access for accessing S3 objects instead of DNS style access. DNS style access is preferred as it will result in better load balancing when accessing S3. | No | `null` (falls back to SDK default)
| `spring.cloud.aws.s3.use-arn-region-enabled` | If an S3 resource ARN is passed in as the target of an S3 operation that has a different region to the one the client was configured with, this flag must be set to 'true' to permit the client to make a cross-region call to the region specified in the ARN otherwise an exception will be thrown. | No | `null` (falls back to SDK default)
| `spring.cloud.aws.s3.crt.minimum-part-size-in-bytes` | Sets the minimum part size for transfer parts. Decreasing the minimum part size causes multipart transfer to be split into a larger number of smaller parts. Setting this value too low has a negative effect on transfer speeds, causing extra latency and network communication for each part. | No | `null` (falls back to SDK default)
| `spring.cloud.aws.s3.crt.initial-read-buffer-size-in-bytes` | Configure the starting buffer size the client will use to buffer the parts downloaded from S3. Maintain a larger window to keep up a high download throughput; parts cannot download in parallel unless the window is large enough to hold multiple parts. Maintain a smaller window to limit the amount of data buffered in memory. | No | `null` (falls back to SDK default)
| `spring.cloud.aws.s3.crt.target-throughput-in-gbps` | The target throughput for transfer requests. Higher value means more S3 connections will be opened. Whether the transfer manager can achieve the configured target throughput depends on various factors such as the network bandwidth of the environment and the configured `max-concurrency` | No | `null` (falls back to SDK default)
| `spring.cloud.aws.s3.crt.max-concurrency` | Specifies the maximum number of S3 connections that should be established during transfer | No | `null` (falls back to SDK default)
| `spring.cloud.aws.s3.transfer-manager.max-depth` | Specifies the maximum number of levels of directories to visit in `S3TransferManager#uploadDirectory` operation | No | `null` (falls back to SDK default)
| `spring.cloud.aws.s3.transfer-manager.follow-symbolic-links` | Specifies whether to follow symbolic links when traversing the file tree in `S3TransferManager#uploadDirectory` operation | No | `null` (falls back to SDK default)
|===

=== Client customization

`S3Client` can be further customized by providing a bean of type `S3ClientCustomizer`:

[source,java]
----
@Bean
S3ClientCustomizer customizer() {
	return builder -> {
		builder.overrideConfiguration(builder.overrideConfiguration().copy(c -> {
			c.apiCallTimeout(Duration.ofMillis(1500));
		}));
	};
}
----

[WARNING]
====
`builder.overrideConfiguration(..)` replaces the configuration object, so always make sure to use `builder.overrideConfiguration().copy(c -> ..)` to configure only certain properties and keep the already pre-configured values for others.
====

`S3ClientCustomizer` is a functional interface that enables configuring `S3ClientBuilder` before the `S3Client` is built in auto-configuration.

There can be multiple `S3ClientCustomizer` beans present in a single application context. The `@Order(..)` annotation can be used to define the order of execution.

Note that `S3ClientCustomizer` beans are applied **after** `AwsSyncClientCustomizer` beans and therefore can overwrite previously set configurations.

=== Loading external configuration

Just as Spring Boot supports configuring an application through an `application.properties` file stored in the file system, the Spring Cloud AWS S3 integration extends this capability by fetching application configuration from an S3 bucket via the `spring.config.import` property.

For example, assuming that there is a file `config.properties` in a bucket named `bucket-name`, to include it as Spring Boot configuration, add the following property to `application.properties` or `application.yml`:

[source,properties]
----
spring.config.import=aws-s3:/bucket-name/config.properties
----

If a file with the given name does not exist in S3, the application will fail to start. If the file configuration is not required for the application and it should continue to start up even when the file is missing, add `optional` before the prefix:

[source,properties]
----
spring.config.import=optional:aws-s3:/bucket-name/config.properties
----

To load multiple files, separate their names with `;`:

[source,properties]
----
spring.config.import=aws-s3:/bucket-name/config.properties;/another-name/config.yml
----

If some files are required and others are optional, list them as separate entries in the `spring.config.import` property:

[source,properties]
----
spring.config.import[0]=optional:bucket-name/config.properties
spring.config.import[1]=aws-s3=/another-name/config.yml
----

Fetched file configuration can be referenced with `@Value`, bound to `@ConfigurationProperties` classes, or referenced in the `application.properties` file.

`JSON`, Java properties, and `YAML` configuration file formats are supported.

The file resolved with `spring.config.import` can also be referenced in `application.properties`.
For example, with a file `config.json` containing the following JSON structure:

[source,json]
----
{
      "url": "someUrl"
}
----


A `spring.config.import` entry is added to `application.properties`:

[source, properties]
----
spring.config.import=aws-s3:/bucket-name/config.json
----

The file configuration values can be referenced by JSON key names:

[source, java]
----
@Value("${url}")
private String url;
----

=== Customizing S3Client

To use a custom `S3Client` in `spring.config.import`, provide an implementation of `BootstrapRegistryInitializer`. For example:

[source,java]
----
package com.app;

import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.AwsCredentialsProvider;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;

import org.springframework.boot.BootstrapRegistry;
import org.springframework.boot.BootstrapRegistryInitializer;

public class S3ClientBootstrapConfiguration implements BootstrapRegistryInitializer {

    @Override
    public void initialize(BootstrapRegistry registry) {
        registry.register(S3Client.class, context -> {
            AwsCredentialsProvider awsCredentialsProvider = StaticCredentialsProvider.create(AwsBasicCredentials.create("yourAccessKey", "yourSecretKey"));
            return S3Client.builder().credentialsProvider(awsCredentialsProvider).region(Region.EU_WEST_2).build();
        });
    }
}
----

Note that this class must be listed under the `org.springframework.boot.BootstrapRegistryInitializer` key in `META-INF/spring.factories`:

[source, properties]
----
org.springframework.boot.BootstrapRegistryInitializer=com.app.S3ClientBootstrapConfiguration
----

If you want to use the auto-configured `S3Client` but change the underlying SDK client or `ClientOverrideConfiguration`, you will need to register a bean of type `S3ClientCustomizer`.
Auto-configuration will then configure the `S3Client` bean with the provided values. For example:

[source,java]
----
package com.app;

import io.awspring.cloud.autoconfigure.s3.S3ClientCustomizer;
import java.time.Duration;
import org.springframework.boot.BootstrapRegistry;
import org.springframework.boot.BootstrapRegistryInitializer;
import software.amazon.awssdk.core.client.config.ClientOverrideConfiguration;
import software.amazon.awssdk.http.SdkHttpClient;
import software.amazon.awssdk.http.apache.ApacheHttpClient;
import software.amazon.awssdk.services.s3.S3Client;

class S3ClientBootstrapConfiguration implements BootstrapRegistryInitializer {

	@Override
	public void initialize(BootstrapRegistry registry) {
		registry.register(S3ClientCustomizer.class, context -> (builder -> {
			builder.overrideConfiguration(builder.overrideConfiguration().copy(c -> {
				c.apiCallTimeout(Duration.ofMillis(2001));
			}));
		}));
	}
}
----

=== `PropertySource` reload

Some applications may need to detect changes on external property sources and update their internal status to reflect the new configuration.
The reload feature of the Spring Cloud AWS S3 config import integration is able to trigger an application reload when a related file value changes.

By default, this feature is disabled. You can enable it by using the `spring.cloud.aws.s3.config.reload.strategy` configuration property (for example, in the `application.properties` file) and adding the following dependencies:

[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-commons</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-context</artifactId>
</dependency>
----

The following levels of reload are supported (by setting the `spring.cloud.aws.s3.config.reload.strategy` property):

* `refresh` (default): Only configuration beans annotated with `@ConfigurationProperties` or `@RefreshScope` are reloaded.
This reload level leverages the refresh feature of Spring Cloud Context.

* `restart_context`: The whole Spring `ApplicationContext` is gracefully restarted. Beans are recreated with the new configuration.
In order for the restart context functionality to work properly, you must enable and expose the restart actuator endpoint:
[source,yaml]
====
----
management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: restart
----
====

Assuming that the reload feature is enabled with default settings (`refresh` mode), the following bean is refreshed when the file changes:

====
[source,java]
----
@Configuration
@ConfigurationProperties(prefix = "bean")
public class MyConfig {

    private String message = "a message that can be changed live";

    // getter and setters

}
----
====

To see that changes effectively happen, you can create another bean that prints the message periodically, as follows:

====
[source,java]
----
@Component
public class MyBean {

    @Autowired
    private MyConfig config;

    @Scheduled(fixedDelay = 5000)
    public void hello() {
        System.out.println("The message is: " + config.getMessage());
    }
}
----
====

The reload feature periodically re-creates the configuration from the S3 file to see if it has changed.
You can configure the polling period by using the `spring.cloud.aws.s3.config.reload.period` property (default value is 1 minute).

=== Configuration

The Spring Boot Starter for S3 provides the following configuration options:

[cols="2,3,1,1"]
|===
| Name | Description | Required | Default value
| `spring.cloud.aws.s3.config.enabled` | Enables the S3 config import integration. | No | `true`
| `spring.cloud.aws.s3.config.reload.strategy` | `Enum` | `refresh` | The strategy to use when firing a reload (`refresh`, `restart_context`)
| `spring.cloud.aws.s3.config.reload.period` | `Duration`| `15s` | The period for verifying changes
| `spring.cloud.aws.s3.config.reload.max-wait-time-for-restart` | `Duration`| `2s` | The maximum time between the detection of changes in property source and the application context restart when `restart_context` strategy is used.
|===

=== S3 Vector Client support

https://aws.amazon.com/blogs/aws/introducing-amazon-s3-vectors-first-cloud-storage-with-native-vector-support-at-scale/[S3 Vector Store] is a vector store which supports uploading, storing and querying vectors.
To allow for simpler use of `S3VectorsClient` with the https://github.com/spring-projects/spring-ai[Spring AI] project, or for direct use as a plain client, Spring Cloud AWS supports autoconfiguration of the `S3VectorsClient`.

To enable autoconfiguration, you should add the following dependencies:
[source,xml]
----
<dependency>
    <groupId>io.awspring.cloud</groupId>
    <artifactId>spring-cloud-aws-starter</artifactId>
</dependency>

<dependency>
	<groupId>software.amazon.awssdk</groupId>
	<artifactId>s3vectors</artifactId>
</dependency>
----

Once these dependencies are present, Spring Cloud AWS will automatically create an `S3VectorsClient` bean, which can then be autowired and used.

[cols="2,3,1,1"]
|===
| Name | Description | Required | Default value
| `spring.cloud.aws.s3.vector.config.enabled` | Enables the S3 config import integration. | No | `true`
|===

=== IAM permissions

The following IAM permissions are required by Spring Cloud AWS:

[cols="2,3,1,1"]
|===
| Name | Description | Required | Default value
| `spring.cloud.aws.s3.vector.enabled` | Enables the S3VectorsClient autoconfiguration. | No | `true`
| `spring.cloud.aws.s3.vector.endpoint` | Configures the endpoint used by `S3VectorsClient`. | No | `http://localhost:4566`
| `spring.cloud.aws.s3.vector.region` | Configures the region used by `S3VectorsClient`. | No | `eu-west-1`
|===

=== Example of an IAM policy for the Spring Cloud AWS demo bucket

Sample IAM policy granting access to `spring-cloud-aws-demo` bucket:

[source,json,indent=0]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::spring-cloud-aws-demo"
        },
        {
            "Effect": "Allow",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::spring-cloud-aws-demo/*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::spring-cloud-aws-demo/*"
        }
    ]
}
----

=== Spring Integration support

Starting with version 4.0, Spring Cloud AWS provides https://spring.io/projects/spring-integration[Spring Integration] channel adapters for Amazon S3.

The S3 Channel Adapters are based on the `S3Client` template and `S3TransferManager`.
See their specification and Javadocs for more information.

The S3 Inbound Channel Adapter is represented by the `S3InboundFileSynchronizingMessageSource` and allows pulling S3 objects as files from the S3 bucket to the local directory for synchronization.
This adapter is similar to the Inbound Channel Adapters in the FTP and SFTP Spring Integration modules.
See more information in the https://docs.spring.io/spring-integration/reference/ftp.html[FTP/FTPS Adapters Chapter] for common options or `SessionFactory`, `RemoteFileTemplate` and `FileListFilter` abstractions.

The Java configuration is:

[source,java]
----
@SpringBootApplication
public static class MyConfiguration {

    @Autowired
    private S3Client amazonS3;

    @Bean
    public S3InboundFileSynchronizer s3InboundFileSynchronizer() {
    	S3InboundFileSynchronizer synchronizer = new S3InboundFileSynchronizer(this.amazonS3);
    	synchronizer.setDeleteRemoteFiles(true);
    	synchronizer.setPreserveTimestamp(true);
    	synchronizer.setRemoteDirectory(S3_BUCKET);
    	synchronizer.setFilter(new S3RegexPatternFileListFilter(".*\\.test$"));
    	Expression expression = PARSER.parseExpression("#this.toUpperCase() + '.a'");
    	synchronizer.setLocalFilenameGeneratorExpression(expression);
    	return synchronizer;
    }

    @Bean
    @InboundChannelAdapter(value = "s3FilesChannel", poller = @Poller(fixedDelay = "100"))
    public S3InboundFileSynchronizingMessageSource s3InboundFileSynchronizingMessageSource() {
    	S3InboundFileSynchronizingMessageSource messageSource =
    			new S3InboundFileSynchronizingMessageSource(s3InboundFileSynchronizer());
    	messageSource.setAutoCreateLocalDirectory(true);
    	messageSource.setLocalDirectory(LOCAL_FOLDER);
    	messageSource.setLocalFilter(new AcceptOnceFileListFilter<File>());
    	return messageSource;
    }

    @Bean
    public PollableChannel s3FilesChannel() {
    	return new QueueChannel();
    }
}
----

With this configuration, you receive messages with `java.io.File` `payload` from the `s3FilesChannel` after periodic synchronization of content from the Amazon S3 bucket into the local directory.

The `S3StreamingMessageSource` adapter produces messages with payloads of type `InputStream`, allowing S3 objects to be fetched without writing to the local file system.
Since the session remains open, the consuming application is responsible for closing the session when the file has been consumed.
The session is provided in the closeableResource header (`IntegrationMessageHeaderAccessor.CLOSEABLE_RESOURCE`).
Standard framework components, such as the `FileSplitter` and `StreamTransformer`, will automatically close the session.

The following Spring Boot application provides an example of configuring the S3 inbound streaming adapter using Java configuration:

[source,java]
----
@SpringBootApplication
public class S3JavaApplication {

    public static void main(String[] args) {
        new SpringApplicationBuilder(S3JavaApplication.class)
            .web(false)
            .run(args);
    }

    @Autowired
    private S3Client amazonS3;

    @Bean
    @InboundChannelAdapter(value = "s3Channel", poller = @Poller(fixedDelay = "100"))
    public MessageSource<InputStream> s3InboundStreamingMessageSource() {
        S3StreamingMessageSource messageSource = new S3StreamingMessageSource(template());
        messageSource.setRemoteDirectory(S3_BUCKET);
        messageSource.setFilter(new S3PersistentAcceptOnceFileListFilter(new SimpleMetadataStore(),
                                   "streaming"));
    	return messageSource;
    }

    @Bean
    @Transformer(inputChannel = "s3Channel", outputChannel = "data")
    public org.springframework.integration.transformer.Transformer transformer() {
        return new StreamTransformer();
    }

    @Bean
    public S3RemoteFileTemplate template() {
        return new S3RemoteFileTemplate(new S3SessionFactory(this.amazonS3));
    }

    @Bean
    public PollableChannel s3Channel() {
    	return new QueueChannel();
    }
}
----

NOTE: Unlike the non-streaming inbound channel adapter, this adapter does not prevent duplicates by default.
If you do not delete the remote file and wish to prevent the file from being processed again, you can configure an `S3PersistentFileListFilter` in the `filter` attribute.
If you do not want to persist the state, an in-memory `SimpleMetadataStore` can be used with the filter.
If you also wish to use a filename pattern (or regex), use a `CompositeFileListFilter`.

The `S3MessageHandler` is an Outbound Channel Adapter and allows performing `upload`, `download` and `copy` (see `S3MessageHandler.Command` enum) operations in the provided S3 bucket.

The Java configuration is:

[source,java]
----
@SpringBootApplication
public static class MyConfiguration {

    @Autowired
    private S3AsyncClient amazonS3;

    @Bean
    @ServiceActivator(inputChannel = "s3UploadChannel")
    public MessageHandler s3MessageHandler() {
    	return new S3MessageHandler(this.amazonS3, "my-bucket");
    }

}
----

With this configuration, you can send a message with `java.io.File` as the `payload`, and the `transferManager.upload()` operation will be performed, where the file name is used as an S3 object key.

See the `S3MessageHandler` Javadocs for more information.

NOTE: The AWS SDK recommends using `S3CrtAsyncClient` for `S3TransferManager`; therefore, an `S3AsyncClient.crtBuilder()` has to be used to achieve the required upload and download performance, which is done internally in the `S3MessageHandler` when the `S3CrtAsyncClient`-based constructor is used.

The `S3MessageHandler` can be used as an Outbound Gateway with the `produceReply = true` constructor argument for Java configuration.

The "request-reply" nature of this gateway is async, and the `Transfer` result from the `TransferManager` operation is sent to the `outputChannel`, enabling transfer progress observation in the downstream flow.

The `TransferListener` can be supplied to the `S3MessageHandler` to track the transfer progress per request.

See the `S3MessageHandler` Javadocs for more information.

The Spring Integration dependency (as well as `s3-transfer-manager` and `aws-crt-client`) in the `spring-cloud-aws-s3` module is `optional`, to avoid unnecessary artifacts on the classpath when Spring Integration is not used.
For convenience, a dedicated `spring-cloud-aws-starter-integration-s3` is provided, managing all the required dependencies for Spring Integration support with Amazon S3.

