=== Integrating your Spring Cloud application with the AWS Secrets Manager

Spring Cloud provides support for centralized configuration, which can be read and made available as a regular Spring
`PropertySource` when the application is started. The Secrets Manager Configuration allows you to use this mechanism
with the https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html[AWS Secrets Manager].

Simply add a dependency on the `spring-cloud-starter-aws-secrets-manager-config` starter module to activate the support.
The support is similar to the support provided for the Spring Cloud Config Server or Consul's key-value store:
configuration parameters can be defined to be shared across all services or for a specific service and can be
profile-specific.

All configuration parameters are retrieved from a common path prefix, which defaults to `/secret`. From there shared
parameters are retrieved from a path that defaults to `application` and service-specific parameters use a path that
defaults to the configured `spring.application.name`. You can use both dots and forward slashes to specify the names
of configuration keys. Names of activated profiles will be appended to the path using a separator that defaults to an
underscore.

That means that for a service called `my-service` the module by default would find and use these parameters:
[cols="2*", options="header"]
|===
|Parameter key
|Description

|`/secret/application`
|Shared by all services that have the Configuration support enabled. Can be overridden with a service- or profile-specific property.

|`/secret/application_production`
|Shared by all services that have the Configuration support enabled and have a `production` Spring profile activated.
Can be overridden with a service-specific property.

|`/secret/my-service`
|Specific to the `my-service` service..

|`/secret/my-service_production`
|Specific to the `my-service` service when a `production` Spring profile is activated.
|===

You can configure the following settings in a Spring Cloud `bootstrap.properties` or `bootstrap.yml` file
(note that relaxed property binding is applied, so you don't have to use this exact syntax):
[cols="3*", options="header"]
|===
|Property
|Default
|Explanation

|`aws.secretsmanager.prefix`
|`/secret`
|Prefix indicating first level for every property loaded from the Secrets Manager.
Value must start with a forward slash followed by one or more valid path segments or be empty.

|`aws.secretsmanager.defaultContext`
|`application`
|Name of the context that defines properties shared across all services

|`aws.secretsmanager.profileSeparator`
|`_`
|String that separates an appended profile from the context name. Can only contain
dots, dashes, forward slashes, backward slashes and underscores next to alphanumeric characters.

|`aws.secretsmanager.failFast`
|`true`
|Indicates if an error while retrieving the secrets should fail starting the application.

|`aws.secretsmanager.name`
|the configured value for `spring.application.name`
|Name to use when constructing the path for the properties to look up for this specific service.

|`aws.secretsmanager.enabled`
|`true`
|Can be used to disable the Secrets Manager Configuration support even though the auto-configuration is on the classpath.

|`aws.secretsmanager.region`
|`eu-central-1`
|Can be used to set region for AWSSecretsManagerClient.
|===

In `spring-cloud` `2020.0.0` (aka Ilford), the bootstrap phase is no longer enabled by default. In order
enable it you need an additional dependency:

[source,xml,indent=0]
----
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-bootstrap</artifactId>
  <version>{spring-cloud-version}</version>
</dependency>
----

However, starting at `spring-cloud-aws` `2.3`, allows import default aws secretsmanager keys
[cols="2*", options="header"]
|===
|Property
|Description

|`spring.config.import=aws-secretsmanager:`
|Importing parameters based on spring.application.name property value for each active profile

|`spring.config.import=aws-secretsmanager:secret-key;other-secret-key`
|Importing secrets by individual keys

|`spring.config.import=optional:aws-secretsmanager:secret-key;other-secret-key`
|With `optional` application will start even if there is no secret found for specified secret.
|===

Spring Boot 2.4 changed the ways files are loaded which means profile loading has changed for Spring-Cloud-AWS as well.
Each document is separated with `#---` and describes one file. Only document that `spring.config.activate.on-profile` is equal to active profile in Application Context are used.
If active profile is `dev` secretsmanager will try to load from `/config/prod/path/`.
Example of Application.properties way to load secrets for specific profile:

----
spring.config.activate.on-profile=dev
spring.config.import=aws-secretsmanager:/config/prod/path
#---
spring.config.activate.on-profile=dev
spring.config.import= aws-secretsmanager:/other/dev/path
#---
spring.config.activate.on-profile=test
spring.config.import= aws-secretsmanager:/something/test/path
---

If you want to share for example `spring.config.import` between test,dev and qa but don't share endpoint or region configuration something like this can be done.

---
spring.config.activate.on-profile=prod
spring.config.import= aws-secretsmanager:/prod/path
#---
spring.config.activate.on-profile=dev,qa,prod
spring.config.import= aws-secretsmanager:test/path
#---
spring.config.activate.on-profile=qa
aws.secretsmanager.region=us-west-1
#---
spring.config.activate.on-profile=test
aws.secretsmanager.region=eu-east-1
#---
spring.config.activate.on-profile=dev
aws.secretsmanager.endpoint= 127.0.0.1
---

More can be read about loading properties in 2.4 and onwards here: https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4


=== IAM Permissions
Following IAM permissions are required by Spring Cloud AWS:

[cols="2"]
|===
|  Get secret value:
| `secretsmanager:GetSecretValue`


|===

Sample IAM policy granting access to Secret manager:

[source,json,indent=0]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": "yourArn"
        }
    ]
}
----
