[#spring-cloud-aws-secrets-manager]
== Secrets Manager Integration

https://aws.amazon.com/secrets-manager/[Secrets Manager] helps to protect secrets needed to access your applications, services, and IT resources. The service enables you to easily rotate, manage, and retrieve database credentials, API keys, and other secrets throughout their lifecycle.

Spring Cloud AWS adds support for loading configuration properties from Secrets Manager through Spring Boot https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-files-importing[config import feature].

Maven coordinates, using <<index.adoc#bill-of-materials, Spring Cloud AWS BOM>>:

[source,xml]
----
<dependency>
	<groupId>io.awspring.cloud</groupId>
	<artifactId>spring-cloud-aws-starter-secrets-manager</artifactId>
</dependency>
----

=== Loading External Configuration

To fetch secrets from Secrets Manager and add them to Spring's environment properties, add `spring.config.import` property to `application.properties`:

For example, assuming that the secret name in Secrets Manager is `/secrets/database-secrets`:

[source,properties]
----
spring.config.import=aws-secretsmanager:/secrets/database-secrets
----

If a secret with given name does not exist in Secrets Manager, application will fail to start. If secret value is not required for the application, and it should continue to startup even when secret is missing, add `optional` before prefix:

[source,properties]
----
spring.config.import=optional:aws-secretsmanager:/secrets/database-secrets
----

To load multiple secrets, separate their names with `;`:

[source,properties]
----
spring.config.import=aws-secretsmanager:/secrets/database-secrets;/secrets/webclient-secrets
----

If some secrets are required, and other ones are optional, list them as separate entries in `spring.config.import` property:

[source,properties]
----
spring.config.import[0]=optional:aws-secretsmanager=/secrets/required-secret
spring.config.import[1]=aws-secretsmanager=/secrets/optional-secret
----

==== Using Key/value (Json) secrets

Secrets resolved with `spring.config.import` can be also referenced in `application.properties`.
For Key/value (json) secret with name `/secrets/database-secrets` that has key MYSQL_HOST_URL and url as a value, we can reference it in properties by following:

[source, properties]
----
spring.config.import=aws-secretsmanager:/secrets/database-secrets
spring.datasource.url=${MYSQL_HOST_URL}
----

[source, java]
----
@Value("${MYSQL_HOST_URL}"
private String mysqlUrl;
----

==== Using plain text secrets

If plainText secret is used, then we are using secret name to reference it.
For example we will use Certificate saved as plainText type inside of Secrets Manager with name `/secrets/my-certificate`:

[source, properties]
----
spring.config.import=aws-secretsmanager:/secrets/my-certificate
spring.datasource.url=${/secrets/my-certificate}
----

[source, java]
----
@Value("${/secrets/my-certificate}"
private String myCertificate;
----

=== Using SecretsManagerClient

The starter automatically configures and registers a `SecretsManagerClient` bean in the Spring application context. The `SecretsManagerClient` bean can be used to create or retrieve secrets imperatively.

[source,java]
----
import org.springframework.stereotype.Component;
import software.amazon.awssdk.services.secretsmanager.SecretsManagerClient;
import software.amazon.awssdk.services.secretsmanager.model.CreateSecretRequest;
...
@Autowired
private SecretsManagerClient secretsManagerClient;
...
secretsManagerClient.createSecret(CreateSecretRequest.builder().name(name).secretString(secret).build());
----

=== Provide custom Client and Credentials

To provide custom credentials for `SecretsManagerClient` that will be used by `spring.config.import` few things needs to be defined.
Firstly we need to register bean in Bootstrap phase.
This can be done by implementing `BootstrapRegistryInitializer` and overriding `initialize` method where we will register our client.

[source,java]
----
import org.springframework.boot.BootstrapRegistry;
import org.springframework.boot.BootstrapRegistryInitializer;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.AwsCredentialsProvider;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.services.secretsmanager.SecretsManagerClient;

public class SecretsManagerBootstrapConfiguration implements BootstrapRegistryInitializer {

    @Override
    public void initialize(BootstrapRegistry registry) {
            AwsCredentialsProvider awsCredentialsProvider = StaticCredentialsProvider.create(AwsBasicCredentials.create("yourAccessKey", "yourSecretKey")));
            return SecretsManagerClient.builder().credentialsProvider(awsCredentialsProvider).region(Region.of(properties.getRegion())).build();
        });
    }
}
----

After that in `META-INF/spring.factories` you should specify implementation of `BootstrapRegistryInitializer` in our case that will be `SecretsManagerBootstrapConfiguration`.

[source, properties]
----
org.springframework.boot.BootstrapRegistryInitializer=myPackage.SecretsManagerBootstrapConfiguration
----

=== Configuration

The Spring Boot Starter for Secrets Manager provides the following configuration options:

[cols="2,3,1,1"]
|===
| Name | Description | Required | Default value
| `spring.cloud.aws.secretsmanager.endpoint` | Configures endpoint used by `SecretsManagerClient`. | No | NO
| `spring.cloud.aws.secretsmanager.region` | Configures region used by `SecretsManagerClient`. | No | NO
|===

==== IAM Permissions
Following IAM permissions are required by Spring Cloud AWS:

[cols="2"]
|===
|  Get secret value:
| `secretsmanager:GetSecretValue`
|===

Sample IAM policy granting access to Secret manager:

[source,json,indent=0]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": "yourArn"
        }
    ]
}
----

