=== Integrating your Spring Cloud application with the AWS Secrets Manager

Spring Cloud provides support for centralized configuration, which can be read and made available as a regular Spring
`PropertySource` when the application is started. The Secrets Manager Configuration allows you to use this mechanism
with the https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html[AWS Secrets Manager].

Simply add a dependency on the `spring-cloud-starter-aws-secrets-manager-config` starter module to activate the support.
The support is similar to the support provided for the Spring Cloud Config Server or Consul's key-value store:
configuration parameters can be defined to be shared across all services or for a specific service and can be
profile-specific.

All configuration parameters are retrieved from a common path prefix, which defaults to `/secret`. From there shared
parameters are retrieved from a path that defaults to `application` and service-specific parameters use a path that
defaults to the configured `spring.application.name`. You can use both dots and forward slashes to specify the names
of configuration keys. Names of activated profiles will be appended to the path using a separator that defaults to an
underscore.

That means that for a service called `my-service` the module by default would find and use these parameters:
[cols="2*", options="header"]
|===
|parameter key
|description

|`/secret/application`
|Shared by all services that have the Configuration support enabled. Can be overridden with a service- or profile-specific property.

|`/secret/application_production`
|Shared by all services that have the Configuration support enabled and have a `production` Spring profile activated.
Can be overridden with a service-specific property.

|`/secret/my-service`
|Specific to the `my-service` service..

|`/secret/my-service_production`
|Specific to the `my-service` service when a `production` Spring profile is activated.
|===

You can configure the following settings in a Spring Cloud `bootstrap.properties` or `bootstrap.yml` file
(note that relaxed property binding is applied, so you don't have to use this exact syntax):
[cols="3*", options="header"]
|===
|property
|default
|explanation

|`aws.secretsmanager.prefix`
|`/secret`
|Prefix indicating first level for every property loaded from the Secrets Manager.
Value must start with a forward slash followed by one or more valid path segments or be empty.

|`aws.secretsmanager.defaultContext`
|`application`
|Name of the context that defines properties shared across all services

|`aws.secretsmanager.profileSeparator`
|`_`
|String that separates an appended profile from the context name. Can only contain
dots, dashes, forward slashes, backward slashes and underscores next to alphanumeric characters.

|`aws.secretsmanager.failFast`
|`true`
|Indicates if an error while retrieving the secrets should fail starting the application.

|`aws.secretsmanager.name`
|the configured value for `spring.application.name`
|Name to use when constructing the path for the properties to look up for this specific service.

|`aws.secretsmanager.enabled`
|`true`
|Can be used to disable the Secrets Manager Configuration support even though the auto-configuration is on the classpath.
|===
