[#spring-cloud-aws-secrets-manager]
== Secrets Manager Integration

https://aws.amazon.com/secrets-manager/[Secrets Manager] allows to safely store and fetch secrets from safety of cloud in one place.

Maven coordinates, using <<index.adoc#bill-of-materials, Spring Cloud AWS BOM>>:

[source,xml]
----
<dependency>
	<groupId>io.awspring.cloud</groupId>
	<artifactId>spring-cloud-aws-starter-secrets-manager</artifactId>
</dependency>
----

==== Using Secrets Manager integration

On startup `spring.config.import` is used to fetch the secrets by name and insert them into Spring application's Environment.
Since `spring.config.import` is loading Secrets on start up, autoconfiguration and registration of `SecretsManagerClient` bean is done then.
Secrets Manager integration supports both Key/value and plain text types from Secrets Manager.

To fetch Secrets in `Application.properties` add following lines for example:

[source,properties]
----
spring.config.import: aws-secretsmanager:/secrets/spring-cloud-aws-sample-app
logging.level.io.awspring.cloud.secretsmanager: debug
----

Where:
 1. `aws-secretsmanager:` is prefix that defines that Secrets Manager integration is used to fetch.
 2. `/secrets/spring-cloud-aws-sample-app` is name of your secret defined in AWS Secrets Manager.
 3. `logging.level.io.awspring.cloud.secretsmanager: debug` logging level that will be logged when integration is used.

If you don't want your application to fail on startup, for missing Secret, simply add `optional` before prefix.
Also if you want to specify more Secrets separate their names with `;`.
List can be used, if you would for example want to specify optional and non optional secrets:

[source,properties]
----
spring.config.import:
 - optional:aws-secretsmanager: /secrets/spring-cloud-aws-sample-app;/secret/common
 - aws-secretsmanager:/secrets/spring-cloud-aws-sample-app;/secret/common
----

==== Using SecretsManagerClient

Because `SecretsManagerClient` is autoconfigured and registered when `spring.config.import` is called, you can inject and use it in your application to create secret for example.
Secret from environment can also be referenced with `@Value(${mysecretname}`
Example:

[source,java]
----
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import software.amazon.awssdk.services.secretsmanager.SecretsManagerClient;
import software.amazon.awssdk.services.secretsmanager.model.CreateSecretRequest;
import software.amazon.awssdk.services.secretsmanager.model.CreateSecretResponse;

@Component
public class App {

	@Value("$password")
	public String password;
	private static final Logger LOGGER = LoggerFactory.getLogger(App.class);

	public SecretsManagerClient secretsManagerClient;

	@Autowired
	public App(SecretsManagerClient secretsManagerClient) {
		this.secretsManagerClient = secretsManagerClient;
	}

	public void createSecret(String name, String secret) {
		CreateSecretResponse createSecretResponse = secretsManagerClient.createSecret(CreateSecretRequest.builder().name(name).secretString(secret).build());
		LOGGER.info(createSecretResponse.arn());
	}

}
----

Fetched Secrets can also be referenced in Application.properties for example:

[source, properties]
----
spring.datasource.url={$MYSQL_HOST_URL}
----

=== Configuration

The Spring Boot Starter for SNS provides the following configuration options:

[cols="2,3,1,1"]
|===
| Name | Description | Required | Default value
| `spring.cloud.aws.secretsmanager.endpoint` | Configures endpoint used by `SecretsManagerClient`. | No | `http://localhost:4566`
| `spring.cloud.aws.secretsmanager.region` | Configures region used by `SecretsManagerClient`. | No | `eu-west-1`
|===

==== IAM Permissions
Following IAM permissions are required by Spring Cloud AWS:

[cols="2"]
|===
|  Get secret value:
| `secretsmanager:GetSecretValue`
|===

Sample IAM policy granting access to Secret manager:

[source,json,indent=0]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": "yourArn"
        }
    ]
}
----

