[#spring-cloud-aws-sns]
== Spring Cloud AWS SNS

https://aws.amazon.com/sns/[SNS] is a pub/sub messaging service that allows clients to publish notifications to a particuluar topic.
A Spring Boot starter is provided to auto-configure SNS integration beans.

Maven coordinates, using <<index.adoc#bill-of-materials, Spring Cloud AWS BOM>>:

[source,xml]
----
<dependency>
    <groupId>io.awspring.cloud</groupId>
    <artifactId>spring-cloud-starter-aws-sns</artifactId>
</dependency>
----

=== Using SnsTemplate

The starter automatically configures and registers a `SnsTemplate` bean in the Spring application context. `SnsTemplate` is used to publish notifications to SNS service.
It is built on top of Spring Messaging which means it supports `Message` objects for publishing, but also supports conversion of objects to String representation.

[source,java]
----
import io.awspring.cloud.sns.core.SnsTemplate;
import org.springframework.messaging.support.MessageBuilder;
import org.springframework.stereotype.Component;

import static io.awspring.cloud.sns.core.MessageHeaderCodes.NOTIFICATION_SUBJECT_HEADER;

@Component
public class SnsMessageSender {
	private final SnsTemplate snsTemplate;

	public SnsMessageSender(SnsTemplate snsTemplate) {
		this.snsTemplate = snsTemplate;
	}

	void sendMessage() {
		this.snsTemplate.send("arn:someArn", MessageBuilder.withPayload("Spring Cloud AWS SNS Sample!")
			.setHeader(NOTIFICATION_SUBJECT_HEADER, "Some value!").build());

		this.snsTemplate.convertAndSend(arn, new Person("Foo", "Bar"));
    	}

    	class Person {
    		private String firstName;
    		private String lastName;

    		public Person() {
    		}

    		public Person(String firstName, String lastName) {
    			this.firstName = firstName;
    			this.lastName = lastName;
    		}

    		//getters and setter

    	}
}
----

If you want to use your own implementation of converters you can create `SnsTemplate` and pass `MessageConverter` object.

`SnsTemplate` also supports publishing notification by a topic name and by default it uses Caching for referencing topic name to ARN. Publishing notification cannot be done without ARN which means:
*	1. Calling create topic which will return ARN for topic that already exist or create topic and return ARN. (This is default behaviour.)
*	2. Getting list of topics filter the list by finding one that has same name as topic name that is being published to. (This would use pagination and possible more calls to SNS).

You can override this behaviour by creating your own implementation of `TopicArnResolver` and pass it to `SnsTemplate` constructor.

=== Using SnsClient

There are also other features such as creating topics,sending SMS and so on, that SNS can be used for, but is not supported by `SnsTemplate`. For those features `SnsClient` can be easily used, simply inject the Bean since it is created by autoconfiguration.

=== Http Notification Controller Endpoints

SNS integration provides support for HTTP endpoints, to be more specific, it allows subscription to events emitted by topic.
SNS is sending following requests and following annotations are used for it:

* Subscription request -> `@NotificationSubscriptionMapping`
* Notification request -> `@NotificationMessageMapping`
* Unsubscription request -> `@NotificationUnsubscribeMapping`

Annotations support path variable which is actually alias to `RequestMapping` path variable, meaning you can use it to fine grain path of your controller class.
HTTP endpoints are based on Spring MVC controllers. Spring Cloud AWS added some custom argument resolvers to extract the message and subject out of the notification requests.

Example of integration:

[source,java]
----
import io.awspring.cloud.sns.annotation.endpoint.NotificationMessageMapping;
import io.awspring.cloud.sns.annotation.endpoint.NotificationSubscriptionMapping;
import io.awspring.cloud.sns.annotation.endpoint.NotificationUnsubscribeConfirmationMapping;
import io.awspring.cloud.sns.annotation.handlers.NotificationMessage;
import io.awspring.cloud.sns.annotation.handlers.NotificationSubject;
import io.awspring.cloud.sns.handlers.NotificationStatus;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;

@Controller
public class NotificationMappingController {

	private static final Logger LOGGER = LoggerFactory.getLogger(NotificationMappingController.class);

	@import io.awspring.cloud.sns.annotation.endpoint.NotificationMessageMapping;
     import io.awspring.cloud.sns.annotation.endpoint.NotificationSubscriptionMapping;
     import io.awspring.cloud.sns.annotation.endpoint.NotificationUnsubscribeConfirmationMapping;
     import io.awspring.cloud.sns.annotation.handlers.NotificationMessage;
     import io.awspring.cloud.sns.annotation.handlers.NotificationSubject;
     import io.awspring.cloud.sns.handlers.NotificationStatus;
     import org.slf4j.Logger;
     import org.slf4j.LoggerFactory;
     import org.springframework.stereotype.Controller;

     @Controller
     public class NotificationMappingController {

     	private static final Logger LOGGER = LoggerFactory.getLogger(NotificationMappingController.class);

     	@NotificationSubscriptionMapping(path = "/testTopic")
     	public void handleSubscriptionMessage(NotificationStatus status) {
     		status.confirmSubscription();
     	}

     	@NotificationMessageMapping(path = "/testTopic")
     	public void handleNotificationMessage(@NotificationSubject String subject, @NotificationMessage String message) {
     		LOGGER.info("NotificationMessageMapping message is: {}", message);
     		LOGGER.info("NotificationMessageMapping subject is: {}", subject);
     	}

     	@NotificationUnsubscribeConfirmationMapping(path = "/testTopic")
     	public void handleUnsubscribeMessage(NotificationStatus status) {
     		status.confirmSubscription();
     	}

     }(path = "/testTopic")
	public void handleSubscriptionMessage(NotificationStatus status) {
		status.confirmSubscription();
	}

	@NotificationMessageMapping(path = "/testTopic")
	public void handleNotificationMessage(@NotificationSubject String subject, @NotificationMessage String message) {
		LOGGER.info("NotificationMessageMapping message is: {}", message);
		LOGGER.info("NotificationMessageMapping subject is: {}", subject);
	}

	@NotificationUnsubscribeConfirmationMapping(path = "/testTopic")
	public void handleUnsubscribeMessage(NotificationStatus status) {
		status.confirmSubscription();
	}

}
----

=== Configuration

The Spring Boot Starter for SNS provides the following configuration options:

[cols="2,3,1,1"]
|===
| Name | Description | Required | Default value
| `spring.cloud.aws.sns.enabled` | Enables the SNS integration. | No | `true`
| `spring.cloud.aws.sns.endpoint` | Configures endpoint used by `SnsClient`. | No | `http://localhost:4566`
| `spring.cloud.aws.sns.region` | Configures region used by `SnsClient`. | No | `eu-west-1`
|===

==== IAM Permissions
Following IAM permissions are required by Spring Cloud AWS:

[cols="2"]
|===
| To publish notification to topic
| `sns:Publish`

| To publish notification you will also need
| `sns:ListTopics`

| To use Annotation-driven HTTP notification endpoint
| `sns:ConfirmSubscription`

| For resolving topic name to ARN
| `sns:CreateTopic`



|===

Sample IAM policy granting access to SNS:

[source,json,indent=0]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "sns:Publish",
                "sns:ConfirmSubscription"
            ],
            "Resource": "yourArn"
        },
        {
            "Effect": "Allow",
            "Action": "sns:ListTopics",
            "Resource": "*"
        },
        {
        "Effect": "Allow",
        "Action": "sns:CreateTopic",
        "Resource": "*"
        }
    ]
}
----
